# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        provider "aws" {
            region = "ap-southeast-2"
            access_key = var.ACCESS_KEY
            secret_key=  var.SECRET_KEY
        }
