pipeline { 
    agent any 

    environment { 
        dockerimagename = "philipasd/shopping-cart"
    }

    stages{
        stage("Welcome") {
            post{
                always { 
                    echo 'Entering Api Gateay'
                }
            }
        }
        stage('Clone Repository') {
            steps {
                // Checkout the source code
                git url: 'https://github.com/philipdaquin/java_microservices.git'
            }
        }
        stage('Compile') {
            steps { 
                sh "mvn clean install"
            }
        }
        stage('Unit Test') {
			steps {
				sh "mvn test"
			}
		}
        stage('Integration Test') {
            steps { 
                sh "mvn failsafe:integration-test failsafe:verify"
            }
        }
        stage('Package') {
            steps {  
                sh "mvn package -DskipTests"
            }
        }
        stage('Build Docker Image') {
            steps {
                script {
                    dockerImage = docker.build(dockerimagename)
                } 
            }
        }
        stage('Push Docker Image to Docker Hub') {
            environment {
               registryCredential = 'dockerhub-credentials'
           }
            steps { 
                script() { 
                    docker.withDockerRegistry('https://registry.hub.docker.com', registryCredential) { 
                        dockerImage.push()
                        dockerImage.push('latest')
                    }
                }
            }
        }
    }
    post { 
        success {
            echo 'Successful run!'
            echo 'Exiting Api Gateway'
        }
        failure { 
            echo 'Failed build!'
        }
    }
}