# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        variable "ACCESS_KEY" {
            description = "Access value"
            sensitive = true
            type = string
            # default = "XX"
        }
        variable "SECRET_KEY" {
            description="Secret value"
            sensitive = true
            type= string
            # default = "XX"
        }
