# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        data "aws_eks_cluster" "eks" { 
            name = var.eks_name
        }

        data "aws_eks_cluster_auth" "eks" { 
            name = var.eks_name
        }

        provider "helm" {
        kubernetes {
            host                   = data.aws_eks_cluster.eks.endpoint
            cluster_ca_certificate = base64decode(data.aws_eks_cluster.eks.certificate_authority[0].data)
            exec {
                api_version = "client.authentication.k8s.io/v1beta1"
                args        = ["eks", "get-token", "--cluster-name", data.aws_eks_cluster.eks.name]
                command     = "aws"
                }
            }
        }
