pipeline { 
    agent any 
    stages{
        stage("Build Project") { 
            steps { 
                checkout([$class: 'GitSCM', 
                branches: [[name: '*/main']], 
                extensions: [], 
                userRemoteConfigs: [[url: 'https://github.com/philipdaquin/java_microservices']]])

                sh "mvn clean install"
            }
        }

        stage("build docker image") {
            steps { 
                script { 
                    sh 'docker build -t product_service:v1 .'
                }
            }
            steps { 
                script { 
                    sh 'docker tag product_service:v1 philipasd/product_service:v1'
                }
            }
        }
        stage("Push image to hub") {
            script { 
                withCredentials([string(crendentialsId: 'dockerhub-pwd', variable: 'dockerhupwd')]) { 
                    sh 'docker login -philipasd -p ${dockerhub-pwd}'

                    sh 'docker push philipasd/product_service:v1'
                }
            }
        }
        stage("Deploy to kubernetes") {
            steps { 
                script {
                    sh 'minikube start'
                    echo 'kubernetes started successfully'
                }
            }
            steps { 
                script { 
                    kubernetesDeploy (configs: 'product-service-deployment.yaml', kubeconfigId: 'k8sconfigpwd')
                }
            }
        }
    }
}