# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
        variable "ACCESS_KEY" {
            description = "Access value"
            sensitive = true
            type = string
            default = "AKIAX4XPSAWAVSYZKGBL"
        }
        variable "SECRET_KEY" {
            description="Secret value"
            sensitive = true
            type= string
            default = "AwmODfqGDsR9+RaCHZ/6L46GKwKvFHDF6qoirMMm"
        }
